# Funding options for Epstein Suite
# Users can support this transparency project through the following methods

custom: ['https://buy.stripe.com/6oU4gB0vMbasdXqat82VG02', 'https://epsteinsuite.com/contact.php']
